"""Automatic character table generator for axial point groups.

Implements the analytical formulas from:
    Johansson, M. P. & Veryazov, V. (2017).
    "Automatic procedure for generating symmetry adapted wavefunctions."
    J. Cheminformatics 9, 36. https://doi.org/10.1186/s13321-017-0193-3

Character table primer
----------------------
A *character table* is a square array that compactly summarises all the
symmetry properties of a point group.  Each *row* corresponds to an
*irreducible representation* (irrep) — a minimal, indivisible way that
functions (orbitals, vibrations, …) can transform under the group's
symmetry operations.  Each *column* corresponds to a *conjugacy class* —
a set of equivalent symmetry operations (e.g. all three C2 axes in D3h
form one class).

The *character* χ(Î", R) in row Î", column R is the trace of the
matrix that represents operation R in irrep Î".  For 1D irreps the
matrix is just a number (+1 or -1); for 2D irreps it is a 2×2 matrix.

Why 2cos(2πjk/n)?

-----------------
A Cn^k rotation by angle 2πk/n has eigenvalues e^(±2πijk/n) in 2D.
The trace (sum of eigenvalues) of the corresponding 2×2 rotation matrix
is therefore e^(2πijk/n) + e^(-2πijk/n) = 2cos(2πjk/n).  This is the
character of the j-th two-dimensional E irrep under Cn^k.

Gerade / ungerade parity
------------------------
Groups with an inversion centre (Cnh with even n, Dnh, etc.) split every
irrep into two: a *gerade* (g, subscript) version that is symmetric under
inversion (χ(i) = +dim) and an *ungerade* (u) version that is
antisymmetric (χ(i) = -dim).  The g/u distinction is essential for
selection rules in spectroscopy.

Prime / double-prime notation
------------------------------
Cnh groups with *odd* n lack an inversion centre, so the g/u split does
not apply.  Instead the two sets of irreps are distinguished by a prime
(′, symmetric under σh) and a double-prime (″, antisymmetric under σh).

This module generates PointGroup objects for the seven axial families
(Cn, Cnh, Cnv, Sn, Dn, Dnh, Dnd) for arbitrary order n, and exposes a
single public entry point ``generate_point_group``.
"""
from __future__ import annotations

import math
from typing import NamedTuple

from ..operations.operation_label import OperationLabel as OL
from ..operations.operation_label_count import OperationLabelCount
from ..point_groups.irrep_label import IrrepLabel
from ..point_groups.point_group import PointGroup
from ..point_groups.point_group_label import PointGroupLabel
from ..point_groups.point_groups import POINT_GROUPS

_E = OL.Element
_P = OL.Plane
_Pr = OL.Prime
_M = IrrepLabel.Mulliken
_IPar = IrrepLabel.Parity
_IPri = IrrepLabel.Prime
_C = PointGroupLabel.Class

# ---------------------------------------------------------------------------
# Small helper types
# ---------------------------------------------------------------------------

class _RotClass(NamedTuple):
    """A column in a character table derived from a rotation class.

    In a Cn group, the conjugacy classes are {E}, {Cn^1, Cn^(n-1)},
    {Cn^2, Cn^(n-2)}, …  Pairs {Cn^k, Cn^(n-k)} collapse to a single column
    with count=2 because the two operations produce identical characters for
    every irrep (rotating clockwise by 2πk/n and anticlockwise by the same
    amount give the same trace).  When k = n/2 exactly (only possible for even
    n), the operation is its own inverse (C2 = Cn^(n/2)) and count=1.

    Fields
    ------
    count : int   Number of operations in this class (1 or 2).
    label : OL    The Schoenflies label written in the column header.
    k : int       The power index k; used in χ = 2cos(2πjk/n).
    """
    count: int          # multiplicity (1 or 2)
    label: OL           # operation label for the column header
    k: int              # power index used in character formulas


# ---------------------------------------------------------------------------
# Shared low-level utilities
# ---------------------------------------------------------------------------

def _divisor_rotation_degrees(n: int) -> set[int]:
    """Return the set of proper rotation degrees generated by a Cn axis."""
    return {n // math.gcd(n, k) for k in range(1, n)}


def _rotation_classes_cn(n: int) -> list[_RotClass]:
    """Build the (count, label, k) list for Cn rotation columns (k=1..⌊n/2⌋).

    Pairs {C_n^k, C_n^(n-k)} collapse to one column of count 2.
    For even n, k=n/2 gives the unique C2 (count 1).
    The label uses the reduced degree n//gcd(n,k) and multiple k//gcd(n,k).
    """
    classes: list[_RotClass] = []
    for k in range(1, n // 2 + 1):
        g = math.gcd(n, k)
        d = n // g      # actual rotation degree
        m = k // g      # power within that degree
        count = 1 if (n % 2 == 0 and k == n // 2) else 2
        lbl = OL(_E.C, d, m)
        classes.append(_RotClass(count=count, label=lbl, k=k))
    return classes


def _improper_classes_cnh_even(n: int) -> list[_RotClass]:
    """Build S-operation columns for even-n Cnh (k=1..n/2-1).

    Each C_n^k · σh pair contributes one column; the label uses the
    reduced improper-rotation degree.
    """
    classes: list[_RotClass] = []
    for k in range(1, n // 2):
        g = math.gcd(n, k)
        d = n // g
        m = k // g
        lbl = OL(_E.S, d, m)
        classes.append(_RotClass(count=2, label=lbl, k=k))
    return classes


def _improper_classes_cnh_odd(n: int) -> list[_RotClass]:
    """Build S-operation columns for odd-n Cnh (odd k = 1,3,...,n-2).

    Each odd-k pair contributes one column with its reduced improper degree.
    """
    classes: list[_RotClass] = []
    for k in range(1, n, 2):          # k = 1, 3, 5, ..., n-2  (n is odd â†' n-1 is even)
        if k >= n:
            break
        g = math.gcd(n, k)
        d = n // g
        m = k // g
        lbl = OL(_E.S, d, m)
        classes.append(_RotClass(count=2, label=lbl, k=k))
    return classes


def _num_proper_cn(n: int) -> dict[int, int]:
    """Minimal proper-rotation count dict for a Cn-type axis (threshold style)."""
    return {d: 1 for d in _divisor_rotation_degrees(n)}


# ---------------------------------------------------------------------------
# Character helpers
# ---------------------------------------------------------------------------

def _chi_cn_k(j: int, k: int, n: int) -> float:
    """χ(E_j, C_n^k) = 2 cos(2π j k / n).

    This is the character of the j-th doubly-degenerate (E-type) irrep
    under the conjugacy class containing Cn^k.  The derivation is given in
    the module docstring.  For the non-degenerate irreps (A, B) the
    characters are ±1 and are handled separately.
    """
    return 2.0 * math.cos(2.0 * math.pi * j * k / n)


# ---------------------------------------------------------------------------
# Irrep-label helpers
# ---------------------------------------------------------------------------

def _cn_irreps(n: int) -> list[IrrepLabel]:
    """Mulliken irrep labels for Cn.

    Cn has n irreps in total (one per conjugacy class):
    - One A irrep (symmetric under all Cn rotations — character = 1 always).
    - One B irrep if n is even (alternates ±1 under rotations; B does not
      exist for odd n because there is no half-turn C2 = Cn^(n/2)).
    - (n-2)/2 doubly-degenerate E irreps for even n, (n-1)/2 for odd n.
      They are numbered E1, E2, … when more than one exists.

    Total check: A (1) + B (0 or 1) + 2*(num_E) = n âœ"
    """
    irreps: list[IrrepLabel] = [IrrepLabel(_M.A)]
    if n % 2 == 0:
        irreps.append(IrrepLabel(_M.B))
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    for j in range(1, num_e + 1):
        sub = j if num_e > 1 else 0   # no subscript if only one E irrep
        irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))
    return irreps


def _e_subscript(j: int, num_e: int) -> int:
    """Return subscript for E_j; 0 means no subscript (used when only one E)."""
    return j if num_e > 1 else 0


# ---------------------------------------------------------------------------
# _build_cn
# ---------------------------------------------------------------------------

def _build_cn(n: int) -> PointGroup:
    """Generate the character table for cyclic group Cn (n ≥ 2).

    Cn is the simplest axial group: just one n-fold rotation axis Cn with no
    mirror planes or inversion.  Examples: H2O2 in its twisted conformation
    (C2), a chiral propeller shape (C3), etc.

    Structure of the character table:
    - Columns: E (identity, implicit), then one column per conjugacy class
      {Cn^k, Cn^(n-k)} for k=1..n/2.
    - Rows: A irrep (all 1s), B irrep (only for even n), E_j irreps.
    """
    rot_cls = _rotation_classes_cn(n)
    num_cols = 1 + len(rot_cls)  # E (implicit) + rotation cols

    # unique_operations (E is implicit, not listed)
    unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]

    # irreps
    irreps = _cn_irreps(n)

    # character table  [irrep_index][col_index]
    # col 0 = E (implicit), col j+1 = rotation class j
    chars: list[list[float]] = []

    # A row: all 1s
    chars.append([1.0] * num_cols)

    # B row (n even): χ(E)=1, χ(class k) = (-1)^k
    if n % 2 == 0:
        b_row = [1.0] + [float((-1) ** rc.k) for rc in rot_cls]
        chars.append(b_row)

    # E_j rows
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    for j in range(1, num_e + 1):
        row = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
        chars.append(row)

    return PointGroup(
        PointGroupLabel(_C.C, n),
        order=n,
        num_inversions=0,
        num_proper_rotations=_num_proper_cn(n),
        num_improper_rotations={},
        num_reflections=0,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


# ---------------------------------------------------------------------------
# _build_cnh
# ---------------------------------------------------------------------------

def _build_cnh(n: int) -> PointGroup:
    """Generate the character table for Cnh (n ≥ 2).

    Cnh adds a horizontal mirror plane σh perpendicular to the Cn axis.
    This doubles the number of operations (and irreps) compared to Cn.
    Example: C2h (trans-N2F2, trans-1,2-dibromoethene).

    Even n vs odd n — a fundamental split
    --------------------------------------
    When n is even, Cnh contains an inversion centre i (because σh combined
    with the C2 = Cn^(n/2) gives i).  The irreps then come in gerade (g)
    and ungerade (u) pairs — every Cn irrep appears twice, once symmetric
    under i (g) and once antisymmetric (u).  Column order follows the
    convention: [Cn rotation cols, i, S cols, σh].

    When n is odd, no inversion centre exists (σh ∘ Cn^(n/2) would require
    n/2 to be an integer, which it isn't for odd n).  Instead, the doubling
    is expressed by a prime (′, symmetric under σh) vs double-prime (″,
    antisymmetric under σh) labelling.  Column order: [Cn cols, σh, S cols].
    """
    rot_cls = _rotation_classes_cn(n)

    if n % 2 == 0:
        # Even n: Cnh = Cn × Ci, so every irrep pairs as g/u
        # Column order: [Cn rotation cols, i, S cols k=1..n/2-1, σh]
        s_cls = _improper_classes_cnh_even(n)

        # unique_operations
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(1, OL(_E.I)))
        unique_ops += [OperationLabelCount(sc.count, sc.label) for sc in s_cls]
        unique_ops.append(OperationLabelCount(1, OL(_E.sigma, _P.h)))

        # irreps (g then u)
        cn_irreps_base = _cn_irreps(n)
        irreps_g = [_add_parity(ir, _IPar.g) for ir in cn_irreps_base]
        irreps_u = [_add_parity(ir, _IPar.u) for ir in cn_irreps_base]
        irreps = irreps_g + irreps_u

        # character table: Cn-part + [i=E-col, S-cols same as rot cols, σh=C2-col]
        # For gerade (g) irreps, the extra columns (i, S, σh) have the same
        # characters as the corresponding Cn columns (symmetric under inversion).
        # For ungerade (u) irreps, all extra-column characters are negated.
        num_rot_cols = 1 + len(rot_cls)
        num_extra = 1 + len(s_cls) + 1    # i + S cols + σh

        def _build_row_cnh_even(cn_row: list[float], parity: int) -> list[float]:
            # cn_row: E + Cn rotation values
            # extra cols: i corresponds to E col (index 0),
            #   S^k cols correspond to matching rot col by same k,
            #   σh corresponds to C2 = last Cn col
            extra: list[float] = []
            # i â†" E col (index 0)
            extra.append(cn_row[0] * parity)
            # S^k cols: same k-order as Cn rotation cols
            for sc in s_cls:
                # find matching Cn col index for the same k
                matching_idx = next(
                    (i + 1 for i, rc in enumerate(rot_cls) if rc.k == sc.k), None
                )
                val = cn_row[matching_idx] if matching_idx is not None else cn_row[0]
                extra.append(val * parity)
            # σh â†" C2 col (last Cn col)
            extra.append(cn_row[-1] * parity)
            return cn_row + extra

        # Build Cn rows first (shared between g and u, different in extra cols)
        cn_chars = _cn_char_rows(n, rot_cls)
        chars = [_build_row_cnh_even(row, +1) for row in cn_chars]   # g
        chars += [_build_row_cnh_even(row, -1) for row in cn_chars]  # u

        num_inversions = 1
        num_improper = {sc.label.get_degree(): 1 for sc in s_cls}

    else:
        # Odd n: use ' / '' prime notation
        # Column order: [Cn rotation cols, σh, S cols k=1,3,...,n-2]
        s_cls = _improper_classes_cnh_odd(n)

        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(1, OL(_E.sigma, _P.h)))
        unique_ops += [OperationLabelCount(sc.count, sc.label) for sc in s_cls]

        # irreps: A', A'', E_j', E_j''
        num_e = (n - 1) // 2
        irreps_prime: list[IrrepLabel] = [IrrepLabel(_M.A, _IPri.Single)]
        irreps_pp: list[IrrepLabel] = [IrrepLabel(_M.A, _IPri.Double)]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            if sub:
                irreps_prime.append(IrrepLabel(_M.E, sub, _IPri.Single))
                irreps_pp.append(IrrepLabel(_M.E, sub, _IPri.Double))
            else:
                irreps_prime.append(IrrepLabel(_M.E, _IPri.Single))
                irreps_pp.append(IrrepLabel(_M.E, _IPri.Double))
        irreps = irreps_prime + irreps_pp

        # characters
        # col 0 = E (implicit), cols 1..len(rot_cls) = rotation, next = σh,
        # then S cols
        cn_chars = _cn_char_rows(n, rot_cls)

        def _add_cnh_odd_extra(cn_row: list[float], sign: int) -> list[float]:
            # σh: sign * dim (for A: ±1, for E: ±2)
            dim = cn_row[0]
            sigma_h_val = sign * dim
            # S cols: χ(S_n^k) = sign * χ(C_n^k).
            # Since the rotation classes pair {k, n-k}, canonicalize to min(k, n-k).
            s_vals: list[float] = []
            for sc in s_cls:
                k_canon = min(sc.k, n - sc.k)
                idx = next(
                    (i + 1 for i, rc in enumerate(rot_cls) if rc.k == k_canon), None
                )
                val = cn_row[idx] if idx is not None else cn_row[0]
                s_vals.append(val * sign)
            return cn_row + [sigma_h_val] + s_vals

        chars = [_add_cnh_odd_extra(row, +1) for row in cn_chars]   # prime
        chars += [_add_cnh_odd_extra(row, -1) for row in cn_chars]  # double-prime

        num_inversions = 0
        num_improper = {n: 1}

    return PointGroup(
        PointGroupLabel(_C.Ch, n),
        order=2 * n,
        num_inversions=num_inversions,
        num_proper_rotations=_num_proper_cn(n),
        num_improper_rotations=num_improper,
        num_reflections=1,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


def _cn_char_rows(n: int, rot_cls: list[_RotClass]) -> list[list[float]]:
    """Return the Cn character table rows (A, [B], E_j) in list-of-rows form."""
    rows: list[list[float]] = []
    rows.append([1.0] * (1 + len(rot_cls)))  # A
    if n % 2 == 0:
        rows.append([1.0] + [float((-1) ** rc.k) for rc in rot_cls])  # B
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    for j in range(1, num_e + 1):
        rows.append([2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls])
    return rows


def _add_parity(ir: IrrepLabel, par: IrrepLabel.Parity) -> IrrepLabel:
    """Return a new IrrepLabel with the given parity appended."""
    m = ir.get_mulliken()
    s = ir.get_subscript()
    if s:
        return IrrepLabel(m, s, par)
    return IrrepLabel(m, par)


# ---------------------------------------------------------------------------
# _build_cnv
# ---------------------------------------------------------------------------

def _build_cnv(n: int) -> PointGroup:
    """Generate the character table for Cnv (n ≥ 2).

    Cnv adds n vertical mirror planes σv containing the Cn axis (no inversion).
    Examples: C2v (water, SO2), C3v (ammonia, PCl3), C4v (SF5Cl).

    For even n, the n planes split into two sets of n/2:
        σv planes pass through atoms (or bonds)
        σd planes bisect pairs of adjacent σv planes (dihedral mirrors)
    These give two separate columns in the character table.

    For odd n, all n planes are equivalent (one σv column).

    Key characters for the reflection columns:
        A1: +1 (symmetric under all reflections)
        A2: -1 (antisymmetric under all reflections)
        B1/B2: ±1 (for even n, distinguishing σv from σd)
        E_j:   0  (the 2D representations are zero for reflections — the trace
                   of a 2D reflection matrix is always 0)
    """
    rot_cls = _rotation_classes_cn(n)
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2

    if n % 2 == 0:
        # n/2 σv + n/2 σd columns — two inequivalent sets of vertical planes
        n_sigma_v = n // 2
        n_sigma_d = n // 2
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n_sigma_v, OL(_E.sigma, _P.v)))
        unique_ops.append(OperationLabelCount(n_sigma_d, OL(_E.sigma, _P.d)))

        # irreps: A1, A2, B1, B2, E_1, ..., E_{n/2-1}
        irreps: list[IrrepLabel] = [
            IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2),
            IrrepLabel(_M.B, 1), IrrepLabel(_M.B, 2),
        ]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        # characters: [rot cols, σv col, σd col]
        # A1: all 1s
        # A2: 1 at rotations, âˆ'1 at σv and σd
        # B1: Cn-B chars at rotations, +1 at σv, âˆ'1 at σd
        # B2: Cn-B chars at rotations, âˆ'1 at σv, +1 at σd
        # E_j: Cn-E_j chars at rotations, 0 at σv, 0 at σd
        b_rot = [1.0] + [float((-1) ** rc.k) for rc in rot_cls]
        chars = []
        chars.append([1.0] * (1 + len(rot_cls)) + [1.0, 1.0])   # A1
        chars.append([1.0] * (1 + len(rot_cls)) + [-1.0, -1.0]) # A2
        chars.append(b_rot + [1.0, -1.0])   # B1
        chars.append(b_rot + [-1.0, 1.0])   # B2
        for j in range(1, num_e + 1):
            e_row = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
            chars.append(e_row + [0.0, 0.0])

    else:
        # n σv columns (no σd for odd n)
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n, OL(_E.sigma, _P.v)))

        # irreps: A1, A2, E_1, ..., E_{(n-1)/2}
        irreps = [IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2)]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        chars = []
        chars.append([1.0] * (1 + len(rot_cls)) + [1.0])   # A1
        chars.append([1.0] * (1 + len(rot_cls)) + [-1.0])  # A2
        for j in range(1, num_e + 1):
            e_row = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
            chars.append(e_row + [0.0])

    return PointGroup(
        PointGroupLabel(_C.Cv, n),
        order=2 * n,
        num_inversions=0,
        num_proper_rotations=_num_proper_cn(n),
        num_improper_rotations={},
        num_reflections=n,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


# ---------------------------------------------------------------------------
# _build_sn
# ---------------------------------------------------------------------------

def _build_sn(n: int) -> PointGroup:
    """Generate the character table for Sn (n even, n ≥ 4).

    Sn is the "improper rotation group": it contains only an n-fold improper
    rotation axis Sn (rotation + perpendicular reflection) and its powers.
    No mirror planes and no Cn axis are independently present.
    Examples: S4 (allene at non-equilibrium twist angle), S6 (staggered ethane).

    The powers S_n^k alternate between proper and improper:
        k odd  â†' S_n^k is a genuine improper rotation
        k even â†' S_n^k = C_{n/2}^{k/2} is a proper rotation

    Why even n only?
    ----------------
    For odd n, S_n contains a horizontal mirror (S_n^n = σh), which makes it
    a Cnh group instead.  The pure "improper only" Sn groups require even n.

    n ≡ 2 mod 4 special case (S6, S10, …)
    --------------------------------------
    When n ≡ 2 mod 4, the group contains an inversion centre (S_n^{n/2} = i),
    so irreps split into g/u pairs.  The column order is rearranged to match
    the convention: proper columns first, then i, then improper columns.

    Sn contains alternating proper (S_n^even = C_{n/2}^k) and improper
    (S_n^odd) operations.  The universal formula χ(E_j, S_n^k) = 2cos(2πjk/n)
    applies to all k (the gerade sign flip for n≡2 mod 4 is handled explicitly).
    """
    if n % 2 != 0 or n < 4:
        raise ValueError(f"Sn group requires even n ≥ 4, got n={n}")

    has_inversion = (n % 4 == 2)  # n ≡ 2 mod 4  (S6, S10, S14, ...)

    # Build column list: alternating (S_n^odd, C_{n/2}^even) for k=1..n/2
    # S_n has order n; we list k=1..n/2 in ascending order.
    col_list: list[_RotClass] = []
    for k in range(1, n // 2 + 1):
        g = math.gcd(n, k)
        d = n // g
        m = k // g
        count = 1 if k == n // 2 else 2
        if k % 2 == 1:
            # improper S column
            lbl = OL(_E.S, d, m)
        else:
            # proper C column (S_n^even = C_{n/2}^{k/2})
            lbl = OL(_E.C, d, m)
        col_list.append(_RotClass(count=count, label=lbl, k=k))

    # Reorder for n≡2 mod 4: proper cols first, then i, then improper cols
    # (matches existing S6 and S10 layout)
    if has_inversion:
        proper_cols = [rc for rc in col_list if rc.k % 2 == 0 and rc.k != n // 2]
        inv_col = next(rc for rc in col_list if rc.k == n // 2)   # i at k=n/2
        # Exclude the inversion (k=n/2) from improper cols — it is listed separately
        improper_cols = [rc for rc in col_list if rc.k % 2 == 1 and rc.k != n // 2]
        ordered_cols = proper_cols + [inv_col] + improper_cols
    else:
        # n≡0 mod 4: ascending k order (matches existing S4, S8)
        ordered_cols = col_list

    unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in ordered_cols]

    # Count proper/improper
    num_proper: dict[int, int] = {}
    num_improper: dict[int, int] = {}
    for rc in col_list:
        if rc.label.get_element() == _E.C:
            num_proper[rc.label.get_degree()] = 1
        elif rc.label.get_element() == _E.S:
            num_improper[rc.label.get_degree()] = 1

    if has_inversion:
        # irreps: Ag, [E_jg], Au, [E_ju]
        # Sn with n≡2 mod 4 is based on C_{n/2} (odd order); its E count is (n-2)//4
        num_e = (n - 2) // 4
        irreps_g: list[IrrepLabel] = [IrrepLabel(_M.A, _IPar.g)]
        irreps_u: list[IrrepLabel] = [IrrepLabel(_M.A, _IPar.u)]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps_g.append(IrrepLabel(_M.E, sub, _IPar.g) if sub else IrrepLabel(_M.E, _IPar.g))
            irreps_u.append(IrrepLabel(_M.E, sub, _IPar.u) if sub else IrrepLabel(_M.E, _IPar.u))
        irreps = irreps_g + irreps_u

        # Characters:
        # g irreps: at even k use +formula, at odd k and k=n/2 use -(formula)
        # u irreps: +formula for all k
        def _sn_chi(j: int, rc: _RotClass, parity: int) -> float:
            val = 2.0 * math.cos(2.0 * math.pi * j * rc.k / n)
            if parity == 1 and (rc.k % 2 == 1 or rc.k == n // 2):
                val = -val
            return val

        def _sn_row_1d(parity: int) -> list[float]:
            # 1D A irrep: 1 at even-k cols (proper), parity*1 at odd-k/inv cols
            row = [1.0]   # E col
            for rc in ordered_cols:
                if rc.k % 2 == 0 and rc.k != n // 2:
                    row.append(1.0)
                else:
                    row.append(float(parity))
            return row

        chars: list[list[float]] = []
        chars.append(_sn_row_1d(+1))   # Ag
        for j in range(1, num_e + 1):
            row = [2.0] + [_sn_chi(j, rc, +1) for rc in ordered_cols]
            chars.append(row)
        chars.append(_sn_row_1d(-1))   # Au
        for j in range(1, num_e + 1):
            row = [2.0] + [_sn_chi(j, rc, -1) for rc in ordered_cols]
            chars.append(row)

        num_inversions = 1

    else:
        # n≡0 mod 4: irreps A, B, E_1, ..., E_{n/2-1}
        num_e = n // 2 - 1
        irreps = [IrrepLabel(_M.A), IrrepLabel(_M.B)]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        # A: all 1s.  B: 1 at even k, -1 at odd k (same (-1)^k formula).
        # E_j: 2cos(2πjk/n) for all k.
        chars = []
        chars.append([1.0] * (1 + len(ordered_cols)))  # A
        b_row = [1.0] + [float((-1) ** rc.k) for rc in ordered_cols]
        chars.append(b_row)
        for j in range(1, num_e + 1):
            row = [2.0] + [2.0 * math.cos(2.0 * math.pi * j * rc.k / n)
                           for rc in ordered_cols]
            chars.append(row)

        num_inversions = 0

    return PointGroup(
        PointGroupLabel(_C.S, n),
        order=n,
        num_inversions=num_inversions,
        num_proper_rotations=num_proper,
        num_improper_rotations=num_improper,
        num_reflections=0,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


# ---------------------------------------------------------------------------
# _build_dn
# ---------------------------------------------------------------------------

def _build_dn(n: int) -> PointGroup:
    """Generate the character table for Dn (n ≥ 2).

    Dn adds n horizontal C2 axes perpendicular to the principal Cn axis
    (no mirror planes or inversion centre).  Example: D2 (twisted allene),
    D3 (tris(en)Co³âº tris-chelate propeller), D6 (coronene with a twist).

    For even n, the n horizontal C2 axes split into two inequivalent sets
    of n/2 each:
        C2′  axes pass through pairs of opposite vertices/atoms
        C2″  axes bisect pairs of C2′ axes
    These contribute two separate columns and give rise to B1/B2 irreps.

    For odd n, all n C2 axes are equivalent — one column, no B1/B2.
    """
    rot_cls = _rotation_classes_cn(n)
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2

    if n % 2 == 0:
        # Two sets of n/2 C2' axes (labelled C2' and C2'')
        n2p = n // 2
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n2p, OL(_E.C, 2, _Pr.Single)))
        unique_ops.append(OperationLabelCount(n2p, OL(_E.C, 2, _Pr.Double)))

        irreps: list[IrrepLabel] = [
            IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2),
            IrrepLabel(_M.B, 1), IrrepLabel(_M.B, 2),
        ]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        b_rot = [1.0] + [float((-1) ** rc.k) for rc in rot_cls]
        chars = []
        chars.append([1.0] * (1 + len(rot_cls)) + [1.0, 1.0])   # A1
        chars.append([1.0] * (1 + len(rot_cls)) + [-1.0, -1.0]) # A2
        chars.append(b_rot + [1.0, -1.0])   # B1
        chars.append(b_rot + [-1.0, 1.0])   # B2
        for j in range(1, num_e + 1):
            e_row = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
            chars.append(e_row + [0.0, 0.0])

        num_c2 = n2p + n2p  # n total C2' axes
        num_c2_from_axis = len([d for d in _divisor_rotation_degrees(n) if d == 2])
        # Add the n C2' axes to the degree-2 count
        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    else:
        # Single set of n C2' axes
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n, OL(_E.C, 2, _Pr.Single)))

        irreps = [IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2)]
        for j in range(1, num_e + 1):
            sub = _e_subscript(j, num_e)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        chars = []
        chars.append([1.0] * (1 + len(rot_cls)) + [1.0])   # A1
        chars.append([1.0] * (1 + len(rot_cls)) + [-1.0])  # A2
        for j in range(1, num_e + 1):
            e_row = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
            chars.append(e_row + [0.0])

        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    return PointGroup(
        PointGroupLabel(_C.D, n),
        order=2 * n,
        num_inversions=0,
        num_proper_rotations=np_rot,
        num_improper_rotations={},
        num_reflections=0,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


# ---------------------------------------------------------------------------
# _build_dnh
# ---------------------------------------------------------------------------

def _build_dnh(n: int) -> PointGroup:
    """Generate the character table for Dnh (n ≥ 2).

    Dnh = Dn + σh (horizontal mirror).  Adding σh to Dn doubles the group
    order and doubles the number of irreps.  Examples: D2h (ethylene, naphthalene),
    D3h (BF3, cyclopropane), D6h (benzene, coronene).

    The doubling works exactly as in Cnh:
    - Even n: Dnh contains an inversion centre â†' g/u splitting.
    - Odd n: no inversion â†' ′/″ prime splitting.

    Column order (even n): [Cn rotation cols, C2', C2'', i, Sn cols, σh, σv, σd]
    Column order (odd n):  [Cn rotation cols, C2', σh, Sn cols, σv]

    Character generation for the extra (improper) columns follows the same
    +parity / -parity rule as _build_cnh: each g or ′ irrep repeats the Dn
    characters with a +1 factor; each u or ″ irrep uses a -1 factor.
    """
    rot_cls = _rotation_classes_cn(n)
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    s_cls_even = _improper_classes_cnh_even(n) if n % 2 == 0 else []
    s_cls_odd = _improper_classes_cnh_odd(n) if n % 2 != 0 else []

    if n % 2 == 0:
        # Dnh (even n): Dn cols + [C2', C2''] + [i, Sn cols, σh, σv, σd]
        n2p = n // 2
        # proper rotations part
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n2p, OL(_E.C, 2, _Pr.Single)))
        unique_ops.append(OperationLabelCount(n2p, OL(_E.C, 2, _Pr.Double)))
        # improper part: i, S cols, σh, σv, σd
        unique_ops.append(OperationLabelCount(1, OL(_E.I)))
        unique_ops += [OperationLabelCount(sc.count, sc.label) for sc in s_cls_even]
        unique_ops.append(OperationLabelCount(1, OL(_E.sigma, _P.h)))
        unique_ops.append(OperationLabelCount(n2p, OL(_E.sigma, _P.v)))
        unique_ops.append(OperationLabelCount(n2p, OL(_E.sigma, _P.d)))

        # irreps: g/u pairs of Dn irreps
        dn_irreps = _dn_irreps(n)
        irreps = [_add_parity(ir, _IPar.g) for ir in dn_irreps] + \
                 [_add_parity(ir, _IPar.u) for ir in dn_irreps]

        # Dn character row (rotation + C2' + C2'' parts)
        def _dn_row(j: int) -> list[float]:
            # j < 0: 1D irrep: j=-1 â†' A1, j=-2 â†' A2, j=-3 â†' B1, j=-4 â†' B2
            if j == -1:   # A1: all 1s
                return [1.0] * (1 + len(rot_cls)) + [1.0, 1.0]
            if j == -2:   # A2: rotations +1, C2' and C2'' -1
                return [1.0] * (1 + len(rot_cls)) + [-1.0, -1.0]
            if j == -3:   # B1: B-chars at rotations, +1/-1
                b = [1.0] + [float((-1) ** rc.k) for rc in rot_cls]
                return b + [1.0, -1.0]
            if j == -4:   # B2
                b = [1.0] + [float((-1) ** rc.k) for rc in rot_cls]
                return b + [-1.0, 1.0]
            # E_j
            return [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls] + [0.0, 0.0]

        # Extra (improper) part for even-n Dnh:
        # For g: same sign as Dn row
        # For u: negated
        def _extra_dnh_even(dn_row: list[float], dn_j: int, parity: int) -> list[float]:
            # i â†" E col (index 0)
            extra = [dn_row[0] * parity]
            # S cols (same k as Cn rotation cols)
            for sc in s_cls_even:
                idx = next((i + 1 for i, rc in enumerate(rot_cls) if rc.k == sc.k), None)
                val = dn_row[idx] if idx is not None else dn_row[0]
                extra.append(val * parity)
            # σh â†" C2 col (last Cn rotation col)
            extra.append(dn_row[len(rot_cls)] * parity)   # = Cn C2 col
            # σv â†" C2' col
            c2p_idx = 1 + len(rot_cls)   # index of C2' in dn_row
            extra.append(dn_row[c2p_idx] * parity)
            # σd â†" C2'' col
            extra.append(dn_row[c2p_idx + 1] * parity)
            return dn_row + extra

        # 1D Dn rows
        dn_rows = {
            'A1': _dn_row(-1), 'A2': _dn_row(-2),
            'B1': _dn_row(-3), 'B2': _dn_row(-4),
        }
        for j in range(1, num_e + 1):
            dn_rows[f'E{j}'] = _dn_row(j)

        key_order = ['A1', 'A2', 'B1', 'B2'] + [f'E{j}' for j in range(1, num_e + 1)]

        chars = [_extra_dnh_even(dn_rows[k], 0, +1) for k in key_order]   # g
        chars += [_extra_dnh_even(dn_rows[k], 0, -1) for k in key_order]  # u

        num_inversions = 1
        num_improper = {sc.label.get_degree(): 1 for sc in s_cls_even}
        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    else:
        # Dnh (odd n): ' / ''
        # Dn cols + n·C2' + [σh, Sn cols, n·σv]
        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n, OL(_E.C, 2, _Pr.Single)))
        unique_ops.append(OperationLabelCount(1, OL(_E.sigma, _P.h)))
        unique_ops += [OperationLabelCount(sc.count, sc.label) for sc in s_cls_odd]
        unique_ops.append(OperationLabelCount(n, OL(_E.sigma, _P.v)))

        # irreps: '/ '' pairs of Dn irreps
        dn_irreps = _dn_irreps(n)
        irreps = [_add_prime(ir, _IPri.Single) for ir in dn_irreps] + \
                 [_add_prime(ir, _IPri.Double) for ir in dn_irreps]

        def _dn_row_odd(j: int) -> list[float]:
            if j == -1:   # A1
                return [1.0] * (1 + len(rot_cls)) + [1.0]
            if j == -2:   # A2
                return [1.0] * (1 + len(rot_cls)) + [-1.0]
            return [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls] + [0.0]

        def _extra_dnh_odd(dn_row: list[float], sign: int) -> list[float]:
            dim = dn_row[0]
            sigma_h_val = sign * dim
            s_vals = []
            for sc in s_cls_odd:
                # Canonicalize k to min(k, n-k) for the rotation-class lookup
                k_canon = min(sc.k, n - sc.k)
                idx = next((i + 1 for i, rc in enumerate(rot_cls) if rc.k == k_canon), None)
                val = dn_row[idx] if idx is not None else dn_row[0]
                s_vals.append(val * sign)
            # σv â†" C2' col
            c2p_val = dn_row[1 + len(rot_cls)]
            return dn_row + [sigma_h_val] + s_vals + [c2p_val * sign]

        key_order_odd = ['A1', 'A2'] + [f'E{j}' for j in range(1, num_e + 1)]
        dn_rows_odd = {'A1': _dn_row_odd(-1), 'A2': _dn_row_odd(-2)}
        for j in range(1, num_e + 1):
            dn_rows_odd[f'E{j}'] = _dn_row_odd(j)

        chars = [_extra_dnh_odd(dn_rows_odd[k], +1) for k in key_order_odd]   # prime
        chars += [_extra_dnh_odd(dn_rows_odd[k], -1) for k in key_order_odd]  # double-prime

        num_inversions = 0
        num_improper = {n: 1}
        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    return PointGroup(
        PointGroupLabel(_C.Dh, n),
        order=4 * n,
        num_inversions=num_inversions,
        num_proper_rotations=np_rot,
        num_improper_rotations=num_improper,
        num_reflections=n + 1,     # n vertical + 1 horizontal
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


def _dn_irreps(n: int) -> list[IrrepLabel]:
    """Return Dn irrep labels (before adding parity/prime suffix)."""
    num_e = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    if n % 2 == 0:
        irreps = [IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2),
                  IrrepLabel(_M.B, 1), IrrepLabel(_M.B, 2)]
    else:
        irreps = [IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2)]
    for j in range(1, num_e + 1):
        sub = _e_subscript(j, num_e)
        irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))
    return irreps


def _add_prime(ir: IrrepLabel, pri: IrrepLabel.Prime) -> IrrepLabel:
    """Return a new IrrepLabel with the given prime appended."""
    m = ir.get_mulliken()
    s = ir.get_subscript()
    if s:
        return IrrepLabel(m, s, pri)
    return IrrepLabel(m, pri)


# ---------------------------------------------------------------------------
# _build_dnd
# ---------------------------------------------------------------------------

def _build_dnd(n: int) -> PointGroup:
    """Generate the character table for Dnd (n ≥ 2).

    Dnd adds n dihedral mirror planes σd (bisecting adjacent C2′ axes) to Dn,
    and consequently also contains a S_{2n} improper rotation axis.  Examples:
    D2d (allene, methane at staggered-like geometry), D3d (staggered ethane),
    D5d (staggered ferrocene).

    The group has order 4n and contains a S_{2n} improper rotation axis.

    Interleaved columns (even n)
    ----------------------------
    For even n, the columns of the character table interleave S_{2n} and C_n
    operations:  (S_{2n}^1, C_n^1), (S_{2n}^3, C_n^2), …  This matches the
    ordering in standard textbook Dnd tables.  The character formula uses a
    unified cosine expression — both S and C columns evaluate as
    2cos(πjk/n) where k is the S_{2n}^k index, because for the proper columns
    k = 2p gives 2cos(π·j·2p/n) = 2cos(2πjp/n), which is the standard E formula.

    Even n vs odd n — inversion again
    ----------------------------------
    For odd n, S_{2n}^n = i (inversion), so the group contains i and the
    irreps split into g/u pairs.  For even n, S_{2n}^n = σh which is absent
    from Dnd (it would make it Dnh), so no inversion and no g/u split.

    For even n: no inversion (A/B/E irreps).
    For odd n: has inversion i = S_{2n}^n (g/u labeling).

    Character formulas for E_j:
      χ(C_n^k)       = 2 cos(2π j k / n)
      χ(S_{2n}^k)    = ±2 cos(π j k / n)
        + for even n (and u irreps of odd n)
        âˆ' for g irreps of odd n
    """
    rot_cls = _rotation_classes_cn(n)
    num_e_cn = (n - 2) // 2 if n % 2 == 0 else (n - 1) // 2
    two_n = 2 * n

    if n % 2 == 0:
        # â"€â"€ even n: no inversion, interleaved S_{2n} / C_n columns â"€â"€â"€â"€â"€â"€â"€â"€â"€
        # Column order: (S_{2n}^1, C_n^1), (S_{2n}^3, C_n^2), ..., (S_{2n}^(n-1), C_2),
        #               n·C2', n·σd
        interleaved: list[_RotClass] = []
        for p in range(1, n // 2 + 1):
            # S_{2n}^(2p-1)
            ks = 2 * p - 1
            gs = math.gcd(two_n, ks)
            ds = two_n // gs
            ms = ks // gs
            count_s = 2   # always 2 (ks < n for all p ≤ n/2)
            interleaved.append(_RotClass(count=count_s, label=OL(_E.S, ds, ms), k=ks))
            # C_n^p (= S_{2n}^{2p})
            kc = 2 * p
            gc = math.gcd(two_n, kc)
            dc = two_n // gc
            mc = kc // gc
            count_c = 1 if (kc == n) else 2
            interleaved.append(_RotClass(count=count_c, label=OL(_E.C, dc, mc), k=kc))

        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in interleaved]
        unique_ops.append(OperationLabelCount(n, OL(_E.C, 2, _Pr.Single)))
        unique_ops.append(OperationLabelCount(n, OL(_E.sigma, _P.d)))

        # irreps: A1, A2, B1, B2, E_1 ... E_{n-1}
        num_e_dnd = n - 1
        irreps: list[IrrepLabel] = [
            IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2),
            IrrepLabel(_M.B, 1), IrrepLabel(_M.B, 2),
        ]
        for j in range(1, num_e_dnd + 1):
            sub = _e_subscript(j, num_e_dnd)
            irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))

        # character formula
        def _chi_dnd_even(j: int, rc: _RotClass) -> float:
            # Both S and C columns use 2cos(πjk/n) where k is the S_{2n}^k power index.
            # For C_n^p: k=2p, so 2cos(πj·2p/n) = 2cos(2πjp/n) âœ"
            return 2.0 * math.cos(math.pi * j * rc.k / n)

        chars: list[list[float]] = []
        # A1
        chars.append([1.0] + [1.0] * len(interleaved) + [1.0, 1.0])
        # A2
        chars.append([1.0] + [1.0] * len(interleaved) + [-1.0, -1.0])
        # B1: âˆ'1 at S_{2n} cols, +1 at C cols, +1 C2', âˆ'1 σd
        b1 = [1.0] + [(-1.0 if rc.label.get_element() == _E.S else 1.0)
                       for rc in interleaved] + [1.0, -1.0]
        chars.append(b1)
        # B2: âˆ'1 at S cols, +1 at C cols, âˆ'1 C2', +1 σd
        b2 = [1.0] + [(-1.0 if rc.label.get_element() == _E.S else 1.0)
                       for rc in interleaved] + [-1.0, 1.0]
        chars.append(b2)
        for j in range(1, num_e_dnd + 1):
            row = [2.0] + [_chi_dnd_even(j, rc) for rc in interleaved] + [0.0, 0.0]
            chars.append(row)

        num_inversions = 0
        s_degrees = {two_n // math.gcd(two_n, 2 * p - 1)
                     for p in range(1, n // 2 + 1)}
        num_improper = {d: 1 for d in s_degrees}
        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    else:
        # â"€â"€ odd n: has inversion, g/u, Cn cols first then S_{2n} cols â"€â"€â"€â"€â"€â"€â"€
        # Column order: Cn rotation cols, n·C2', i, S_{2n}^k (k=1,3,...,n-2), n·σd
        s_cols: list[_RotClass] = []
        for p in range(1, (n + 1) // 2):        # p = 1 .. (n-1)/2
            ks = 2 * p - 1                       # odd k values 1, 3, ..., n-2
            gs = math.gcd(two_n, ks)
            ds = two_n // gs
            ms = ks // gs
            s_cols.append(_RotClass(count=2, label=OL(_E.S, ds, ms), k=ks))

        unique_ops = [OperationLabelCount(rc.count, rc.label) for rc in rot_cls]
        unique_ops.append(OperationLabelCount(n, OL(_E.C, 2, _Pr.Single)))
        unique_ops.append(OperationLabelCount(1, OL(_E.I)))
        unique_ops += [OperationLabelCount(sc.count, sc.label) for sc in s_cols]
        unique_ops.append(OperationLabelCount(n, OL(_E.sigma, _P.d)))

        # irreps: g/u pairs; each set has A1, A2, E_1, ..., E_{(n-1)/2}
        num_e_dnd = (n - 1) // 2
        base_irreps: list[IrrepLabel] = [IrrepLabel(_M.A, 1), IrrepLabel(_M.A, 2)]
        for j in range(1, num_e_dnd + 1):
            sub = _e_subscript(j, num_e_dnd)
            base_irreps.append(IrrepLabel(_M.E, sub) if sub else IrrepLabel(_M.E))
        irreps = [_add_parity(ir, _IPar.g) for ir in base_irreps] + \
                 [_add_parity(ir, _IPar.u) for ir in base_irreps]

        # characters for odd-n Dnd:
        # Cn rotation columns: 2cos(2πjk/n)
        # C2' column: 0 for E, ±1 for A
        # i column: +dim for g, âˆ'dim for u
        # S_{2n}^k column: âˆ'2cos(πjk/n) for g, +2cos(πjk/n) for u
        # σd column: 0 for E, ±1 for A

        def _build_dnd_odd_row(j: int, parity: int) -> list[float]:
            # j ≥ 1: E_j;  j == -1: A1;  j == -2: A2
            # parity: +1 for g, -1 for u
            if j == -1:   # A1: C2'=+1, i=+parity, S=+parity, σd=+parity
                rot_part = [1.0] * (1 + len(rot_cls))
                c2p_val = 1.0
                i_val = float(parity)
                s_vals = [float(parity)] * len(s_cols)
                sigma_d_val = float(parity)
            elif j == -2:  # A2: C2'=âˆ'1, i=+parity, S=+parity, σd=âˆ'parity
                rot_part = [1.0] * (1 + len(rot_cls))
                c2p_val = -1.0
                i_val = float(parity)
                s_vals = [float(parity)] * len(s_cols)
                sigma_d_val = float(-parity)
            else:           # E_j
                rot_part = [2.0] + [_chi_cn_k(j, rc.k, n) for rc in rot_cls]
                c2p_val = 0.0
                dim = 2.0
                i_val = dim * parity
                # χ(E_j, S_{2n}^k) = (-1)^j * parity * 2cos(πjk/n)
                # Derived from the D-nd character tables: the sign alternates with j.
                sign = float((-1) ** j * parity)
                s_vals = [
                    sign * 2.0 * math.cos(math.pi * j * sc.k / n)
                    for sc in s_cols
                ]
                sigma_d_val = 0.0

            return rot_part + [c2p_val, i_val] + s_vals + [sigma_d_val]

        j_order = [-1, -2] + list(range(1, num_e_dnd + 1))
        chars = [_build_dnd_odd_row(j, +1) for j in j_order]   # g irreps
        chars += [_build_dnd_odd_row(j, -1) for j in j_order]  # u irreps

        num_inversions = 1
        s_degrees = {two_n // math.gcd(two_n, sc.k) for sc in s_cols}
        num_improper = {d: 1 for d in s_degrees}
        np_rot = dict(_num_proper_cn(n))
        np_rot[2] = np_rot.get(2, 0) + n

    return PointGroup(
        PointGroupLabel(_C.Dd, n),
        order=4 * n,
        num_inversions=num_inversions,
        num_proper_rotations=np_rot,
        num_improper_rotations=num_improper,
        num_reflections=n,
        unique_operations=unique_ops,
        irreps=irreps,
        characters=chars,
    )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

_SUPPORTED_CLASSES = {
    _C.C, _C.Ch, _C.Cv, _C.S, _C.D, _C.Dh, _C.Dd,
}

_BUILDERS = {
    _C.C:  _build_cn,
    _C.Ch: _build_cnh,
    _C.Cv: _build_cnv,
    _C.S:  _build_sn,
    _C.D:  _build_dn,
    _C.Dh: _build_dnh,
    _C.Dd: _build_dnd,
}


def generate_point_group(label: PointGroupLabel) -> PointGroup:
    """Generate a PointGroup with full character table for any axial point group.

    This is the public entry point called by symmetry.py when no hardcoded
    character table matches the detected operations (e.g. a molecule with a
    C15 axis).  It dispatches to the appropriate _build_* function based on
    the group class (Cn, Cnh, Cnv, Sn, Dn, Dnh, Dnd).

    Polyhedral groups (T, O, I) and linear groups (C∞v, D∞h) are NOT supported
    here — they use hardcoded tables in point_groups.py because their structure
    does not fit the uniform axial formulas.

    Supported families: Cn, Cnh, Cnv, Sn (n even ≥ 4), Dn, Dnh, Dnd.
    Raises ValueError for unsupported families (polyhedral, linear, n < 2).
    """
    cls = label.get_class()
    n = label.get_order()

    if cls not in _SUPPORTED_CLASSES:
        raise ValueError(
            f"generate_point_group does not support class {cls.name}; "
            "polyhedral and linear groups use hardcoded tables."
        )
    if n < 2:
        raise ValueError(f"Order must be ≥ 2 for axial groups, got n={n}")
    if cls == _C.S and n % 2 != 0:
        raise ValueError(f"Sn requires even n, got n={n}")
    if cls == _C.S and n < 4:
        raise ValueError(f"Sn requires n ≥ 4, got n={n}")

    return _BUILDERS[cls](n)


def get_or_generate_point_group(label: PointGroupLabel) -> PointGroup | None:
    """Return a PointGroup by label: hardcoded table first, generator fallback.

    Returns None if the label is not in POINT_GROUPS and cannot be generated
    (e.g. polyhedral or linear groups not in the hardcoded list).
    """
    # Search hardcoded list first
    for pg in POINT_GROUPS:
        pg_lbl = pg.get_label()
        if (pg_lbl.get_class() == label.get_class()
                and pg_lbl.get_order() == label.get_order()):
            return pg

    # Try generator
    try:
        return generate_point_group(label)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Name parsing and convenience printer
# ---------------------------------------------------------------------------

# Fixed names that contain no numeric order.
_FIXED_NAMES: dict[str, PointGroupLabel] = {
    "C1":     PointGroupLabel(_C.C,    1),
    "Ci":     PointGroupLabel(_C.Ci),
    "Cs":     PointGroupLabel(_C.Cs),
    "T":      PointGroupLabel(_C.T),
    "Td":     PointGroupLabel(_C.Td),
    "Th":     PointGroupLabel(_C.Th),
    "O":      PointGroupLabel(_C.O),
    "Oh":     PointGroupLabel(_C.Oh),
    "I":      PointGroupLabel(_C.I),
    "Ih":     PointGroupLabel(_C.Ih),
    # linear — accept both the ∞ form and the ASCII "inf" form
    "C∞v":    PointGroupLabel(_C.Cinfv),
    "Cinfv":  PointGroupLabel(_C.Cinfv),
    "D∞h":    PointGroupLabel(_C.Dinfh),
    "Dinfh":  PointGroupLabel(_C.Dinfh),
}

# Suffix â†' PointGroupLabel class for axial groups that carry a numeric order.
_SUFFIX_TO_CLASS: dict[str, _C] = {
    "h":  _C.Ch,
    "v":  _C.Cv,
    "d":  _C.Dd,
    "":   None,   # resolved per leading letter below
}


def parse_point_group_name(name: str) -> PointGroupLabel:
    """Parse a Schoenflies point group name string into a PointGroupLabel.

    Accepted formats
    ----------------
    Fixed-order groups (no integer in the name):
      "C1", "Ci", "Cs"
      "T", "Td", "Th", "O", "Oh", "I", "Ih"
      "C∞v" or "Cinfv"  (linear, no inversion)
      "D∞h" or "Dinfh"  (linear, with inversion)

    Axial groups with integer order *n*:
      Cyclic:       "Cn"          e.g. "C3", "C11"
      Horizontal:   "Cnh"         e.g. "C3h", "C10h"
      Pyramidal:    "Cnv"         e.g. "C3v", "C6v"
      Improper:     "Sn"          e.g. "S4", "S12"  (n must be even and ≥ 4)
      Dihedral:     "Dn"          e.g. "D3", "D6"
      Prismatic:    "Dnh"         e.g. "D3h", "D6h"
      Antiprismatic:"Dnd"         e.g. "D3d", "D4d"

    The name is case-sensitive for the leading letter (C, D, S, T, O, I)
    and case-insensitive for the suffix (h, v, d).

    Examples
    --------
    >>> parse_point_group_name("C3v")
    PointGroupLabel(Cv, 3)
    >>> parse_point_group_name("D6h")
    PointGroupLabel(Dh, 6)
    >>> parse_point_group_name("Oh")
    PointGroupLabel(Oh)

    Raises
    ------
    ValueError
        If the string cannot be parsed or the combination is invalid.
    """
    stripped = name.strip()

    # 1. Fixed-name lookup (case-sensitive as written by get_name())
    if stripped in _FIXED_NAMES:
        return _FIXED_NAMES[stripped]

    # 2. Case-insensitive fallback for the fixed names
    lower = stripped.lower()
    for key, lbl in _FIXED_NAMES.items():
        if key.lower() == lower:
            return lbl

    # 3. Axial groups: split into (leading letter(s)) + (digits) + (trailing suffix)
    import re
    m = re.fullmatch(r'([CDScdsi])(\d+)([hvdHVD]?)', stripped)
    if m is None:
        raise ValueError(
            f"Cannot parse point group name '{name}'. "
            "Expected a Schoenflies symbol such as 'C3v', 'D5h', 'S8', 'D3d'. "
            "See parse_point_group_name docstring for the full list of accepted formats."
        )

    letter  = m.group(1).upper()   # C, D, or S
    n       = int(m.group(2))
    suffix  = m.group(3).lower()   # h, v, d, or empty

    if letter == "S":
        if suffix:
            raise ValueError(f"Sn groups have no suffix; got '{name}'.")
        pg_class = _C.S
    elif letter == "C":
        pg_class = {"h": _C.Ch, "v": _C.Cv, "": _C.C}.get(suffix)
        if pg_class is None:
            raise ValueError(f"Unknown suffix '{suffix}' for C-type group in '{name}'.")
    elif letter == "D":
        pg_class = {"h": _C.Dh, "d": _C.Dd, "": _C.D}.get(suffix)
        if pg_class is None:
            raise ValueError(f"Unknown suffix '{suffix}' for D-type group in '{name}'.")
    else:
        raise ValueError(f"Unexpected leading letter '{letter}' in '{name}'.")

    return PointGroupLabel(pg_class, n)


def print_character_table_for(name: str) -> None:
    """Look up or generate the character table for a point group and print it.

    The *name* must be a Schoenflies symbol in the format described by
    :func:`parse_point_group_name`.  Short summary of accepted formats:

    * Fixed groups — ``"C1"``, ``"Ci"``, ``"Cs"``, ``"T"``, ``"Td"``,
      ``"Th"``, ``"O"``, ``"Oh"``, ``"I"``, ``"Ih"``,
      ``"C∞v"`` / ``"Cinfv"``, ``"D∞h"`` / ``"Dinfh"``
    * Axial groups — ``"Cn"``, ``"Cnh"``, ``"Cnv"``, ``"Sn"``,
      ``"Dn"``, ``"Dnh"``, ``"Dnd"`` where *n* is any valid integer
      (e.g. ``"C3v"``, ``"D6h"``, ``"S12"``, ``"D11"``, ``"C20v"``)

    Groups already in the hardcoded POINT_GROUPS list are used directly;
    all others are generated on-the-fly via the analytical formulas.

    Parameters
    ----------
    name:
        Schoenflies symbol (case-sensitive leading letter, case-insensitive
        suffix).  Whitespace is stripped automatically.

    Raises
    ------
    ValueError
        If *name* cannot be parsed or the requested group is unavailable
        (e.g. polyhedral groups with n > hardcoded limit have no generator).

    Examples
    --------
    >>> print_character_table_for("C3v")
    C3v  |     E |   2C3 |   3σv
    ----------------------------
    A1   |     1 |     1 |     1
    A2   |     1 |     1 |    -1
    E    |     2 |    -1 |     0

    >>> print_character_table_for("D6h")
    ...full 16-row D6h table...

    >>> print_character_table_for("C12v")
    ...generated C12v table for n=12...
    """
    label = parse_point_group_name(name)
    pg = get_or_generate_point_group(label)
    if pg is None:
        raise ValueError(
            f"No character table available for '{name}'. "
            "Polyhedral and linear groups must be in the hardcoded list."
        )
    pg.print_character_table()


# ---------------------------------------------------------------------------
# Example usage (run this module directly: python -m pyrrhotite.character_tables.generator)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _examples = [
        "C1", "Cs", "Ci",
        "C3", "C4v", "C5h", "C6",
        "D3", "D4h", "D5d",
        "S4", "S6",
        "Oh", "Ih",
        "C∞v", "D∞h",
        # Groups beyond the hardcoded list — generated on-the-fly:
        "C11", "C12v", "D11h", "D12d", "S12",
    ]

    for _name in _examples:
        print(f"\n{'='*60}")
        try:
            print_character_table_for(_name)
        except ValueError as _e:
            print(f"[{_name}] {_e}")
